import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/Navbar';
import { cn } from '@/lib/utils';
import Sidebar from '@/components/Sidebar';
import { Providers } from './LayoutContainer';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <Providers>
        <body
          className={cn(' bg-white in-h-screen w-full', {
            'debug-screens': process.env.NODE_ENV === 'development',
          })}
        >
          <Navbar />
          {children}
          <Sidebar />
        </body>
      </Providers>
    </html>
  );
}
